---
settings:
  name: StorageGRID 11.7
  internal:
    pdf_enabled: false
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    hide_language_selector: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de StorageGRID 11,7
    url: "/index.html"
  - title: Notas de la versi칩n
    url: "/release-notes/index.html"
  - title: Manos a la obra
    entries:
    - section: primer
    - section: network
    - title: Inicio r치pido para StorageGRID
      url: "/primer/quick-start.html"
  - title: Instale y actualice
    entries:
    - section: installconfig
    - section: rhel
    - section: ubuntu
    - section: vmware
    - section: upgrade
  - title: Configurar y gestionar
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: Utilice StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: Supervisi칩n y soluci칩n de problemas
    entries:
    - section: monitor
    - section: troubleshoot
    - section: audit
  - title: Mantener
    entries:
    - section: expand
    - section: maintain
    - section: commonhardware
    - section: sg6100
    - section: sg6000
    - section: sg5700
    - section: sg5600
    - section: sg100-1000
  - title: Habilite StorageGRID
    url: "/storagegrid-enable.html"
  - title: Otras versiones
    url: "/earlier-versions.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family
