---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: Antes de actualizar un sistema StorageGRID, es necesario comprobar que el sistema está listo para admitir la actualización. Debe asegurarse de que el sistema se ejecute con normalidad y que todos los nodos de grid estén operativos. 
---
= Compruebe el estado del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de actualizar un sistema StorageGRID, es necesario comprobar que el sistema está listo para admitir la actualización. Debe asegurarse de que el sistema se ejecute con normalidad y que todos los nodos de grid estén operativos.

.Pasos
. Inicie sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
. Compruebe y resuelva cualquier alerta activa.
. Confirme que no hay ninguna tarea de cuadrícula en conflicto activa ni pendiente.
+
.. Seleccione *SUPPORT* > *Tools* > *Topología de cuadrícula*.
.. Seleccione *_site_* > *_primary Admin Node_* > *CMN* > *Grid Tasks* > *Configuration*.
+
Las tareas de evaluación de la gestión del ciclo de vida de la información (ILME) son las únicas tareas de la cuadrícula que se pueden ejecutar simultáneamente con la actualización del software.

.. Si hay otras tareas de cuadrícula activas o pendientes, espere a que finalicen o liberen el bloqueo.
+

NOTE: Póngase en contacto con el soporte técnico si una tarea no finaliza o libera el bloqueo.



. Consulte link:../network/internal-grid-node-communications.html["Comunicaciones internas de los nodos de grid"] y.. link:../network/external-communications.html["Comunicaciones externas"] Para asegurarse de que todos los puertos requeridos para StorageGRID 11,7 se abren antes de la actualización.
+
Lo siguiente link:../network/internal-grid-node-communications.html#storagegrid-internal-ports["puertos internos"] Debe estar abierto antes de actualizar a StorageGRID 11,7:

+
[cols="1a,2a"]
|===
| Puerto | Descripción 


 a| 
1055

8011

10342
 a| 
Se utiliza para el protocolo de golpeteo de los controles del cortafuegos.

Antes de actualizar, confirme que este puerto está abierto entre todos los nodos de cuadrícula de la red.



 a| 
18086
 a| 
Puerto TCP utilizado para el nuevo servicio LDR.

Antes de la actualización, confirme que este puerto está abierto desde todos los nodos de cuadrícula a todos los nodos de almacenamiento.

|===



IMPORTANT: Si ha abierto algún puerto de firewall personalizado, se le notificará durante las comprobaciones previas de la actualización. Debe comunicarse con el soporte técnico antes de continuar con la actualización.
