---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: Antes de iniciar la actualización, debe comprobar que la versión anterior de StorageGRID está actualmente instalada con la revisión más reciente disponible aplicada. 
---
= Comprobar la versión instalada de StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de iniciar la actualización, debe comprobar que la versión anterior de StorageGRID está actualmente instalada con la revisión más reciente disponible aplicada.

.Acerca de esta tarea
Antes de actualizar a StorageGRID 11,7, su grid debe tener instalado StorageGRID 11,6. Si actualmente está utilizando una versión anterior de StorageGRID, debe instalar todos los archivos de actualización anteriores junto con sus revisiones más recientes (muy recomendado) hasta que la versión actual de su grid sea StorageGRID 11,6._x.y_.

En la <<Ejemplo: Actualice a StorageGRID 11,6 desde la versión 11.3.0.8,ejemplo>>.


IMPORTANT: NetApp recomienda encarecidamente que aplique la revisión más reciente para cada versión de StorageGRID antes de actualizar a la siguiente versión y que también aplique la revisión más reciente para cada versión nueva que instale. En algunos casos, debe aplicar una revisión para evitar el riesgo de pérdida de datos. Consulte https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Descargas de NetApp: StorageGRID"^] y las notas de la versión de cada revisión para obtener más información.

Tenga en cuenta que puede ejecutar una secuencia de comandos para actualizar de 11.3.0.13+ a 11.4.0._y_ en un solo paso y de 11.4.0.7+ a 11.5.0._y_ en un solo paso. Consulte https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_run_combined_major_upgrade_and_hotfix_script_for_StorageGRID["Base de conocimientos de NetApp: Cómo ejecutar scripts combinados de actualizaciones importantes y revisiones para StorageGRID"^].

.Pasos
. Inicie sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
. En la parte superior de Grid Manager, seleccione *Ayuda* > *Acerca de*.
. Verifique que *Version* es 11,6._x.y_.
+
En el número de versión de StorageGRID 11,6._x.y_:

+
** La versión *major* tiene un valor _x_ de 0 (11,6.0).
** Un *hotfix*, si se ha aplicado uno, tiene un valor _y_ (por ejemplo, 11,6.0,1).


. Si *Version* no es 11,6._x.y_, vaya a. https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Descargas de NetApp: StorageGRID"^] para descargar los archivos de cada versión anterior, incluida la revisión más reciente de cada versión.
. Obtenga las instrucciones de actualización de cada versión descargada. A continuación, realice el procedimiento de actualización de software para esa versión y aplique la revisión más reciente para esa versión (recomendado expresamente).
+
Consulte link:../maintain/storagegrid-hotfix-procedure.html["Procedimiento de revisión de StorageGRID"].





== Ejemplo: Actualice a StorageGRID 11,6 desde la versión 11.3.0.8

El ejemplo siguiente muestra los pasos para actualizar de la versión 11.3.0.8 de StorageGRID a la versión 11,6 en la preparación para una actualización de StorageGRID 11,7.


IMPORTANT: Opcionalmente, puede ejecutar una secuencia de comandos para combinar los pasos 2 y 3 (actualización de 11.3.0.13+ a 11.4.0._y_) y combinar los pasos 4 y 5 (actualización de 11.4.0.7+ a 11.5.0._y_). Consulte https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_run_combined_major_upgrade_and_hotfix_script_for_StorageGRID["Base de conocimientos de NetApp: Cómo ejecutar scripts combinados de actualizaciones importantes y revisiones para StorageGRID"^].

Descargue e instale software en la siguiente secuencia para preparar el sistema para la actualización:

. Aplique la última revisión StorageGRID 11.3.0._y_.
. Actualice a la versión principal de StorageGRID 11.4.0.
. Aplique la última revisión StorageGRID 11.4.0._y_.
. Actualice a la versión principal de StorageGRID 11.5.0.
. Aplique la última revisión StorageGRID 11.5.0._y_.
. Actualice a la versión principal de StorageGRID 11.6.0.
. Aplique la última revisión de StorageGRID 11,6.0._y_.

