---
permalink: sg100-1000/shut-down-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg1000, SG100, power off, turn off, shut off, shutdown, shut down, 
summary: Apague el dispositivo de servicios para realizar el mantenimiento del hardware. 
---
= Apague el aparato de servicios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Apague el dispositivo de servicios para realizar el mantenimiento del hardware.

.Antes de empezar
* Ya tienes link:locating-controller-in-data-center.html["ubicación física del aparato de servicios"].


.Acerca de esta tarea
Para evitar interrupciones del servicio, apague el dispositivo de servicios durante un periodo de mantenimiento programado cuando normalmente se esperan periodos de interrupción del servicio.

.Pasos
. Apague el aparato:
+

CAUTION: Debe realizar un apagado controlado del dispositivo introduciendo los comandos especificados a continuación. Se recomienda realizar un apagado controlado cuando sea posible para evitar alertas innecesarias, garantizar que haya logs completos disponibles y evitar interrupciones del servicio.

+
.. Inicie sesión en el nodo de la cuadrícula mediante PuTTY u otro cliente ssh:
+
... Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
... Introduzca la contraseña que aparece en `Passwords.txt` archivo.
... Introduzca el siguiente comando para cambiar a la raíz: `su -`
... Introduzca la contraseña que aparece en `Passwords.txt` archivo.
+
Cuando ha iniciado sesión como root, el símbolo del sistema cambia de `$` para `#`.



.. Apague el aparato de servicios: +
`*shutdown -h now*`
+
Este comando puede tardar hasta 10 minutos en completarse.



. Utilice uno de los siguientes métodos para verificar que el aparato está apagado:
+
** Observe el LED de alimentación de la parte frontal del aparato y confirme que está apagado.
** Compruebe la página Power Control de la interfaz del BMC para confirmar que el aparato está apagado.



