---
permalink: ubuntu/installing-linux.html 
sidebar: sidebar 
keywords: how to install Linux 
summary: Debe instalar Ubuntu o Debian en todos los hosts de grid. Utilice la herramienta matriz de interoperabilidad de NetApp para obtener una lista de las versiones compatibles. 
---
= Instale Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe instalar Linux en todos los hosts Grid. Utilice la https://["Herramienta de matriz de interoperabilidad de NetApp (IMT)"^] para obtener una lista de las versiones compatibles.


IMPORTANT: Asegúrese de que su sistema operativo esté actualizado al kernel 4,15 de Linux o superior.

.Pasos
. Instalar Linux en todos los hosts de grid físicos o virtuales de acuerdo con las instrucciones del mayorista o del procedimiento estándar.
+

NOTE: No instale ningún entorno de escritorio gráfico. Al instalar Ubuntu, debe seleccionar *utilidades estándar del sistema*. Se recomienda seleccionar *OpenSSH Server* para habilitar el acceso ssh a sus hosts Ubuntu. Todas las demás opciones pueden permanecer desactivadas.

. Asegúrese de que todos los hosts tengan acceso a los repositorios de paquetes de Ubuntu o Debian.
. Si el intercambio está activado:
+
.. Ejecute el siguiente comando: `$ sudo swapoff --all`
.. Eliminar todas las entradas de intercambio de `/etc/fstab` para mantener los ajustes.
+

IMPORTANT: Si no se deshabilita por completo el intercambio, el rendimiento se puede reducir considerablemente.




