---
permalink: installconfig/configuring-bmc-interface.html 
sidebar: sidebar 
keywords: BMC, baseboard management controller, configure, setup, set up 
summary: 'La interfaz de usuario del controlador de gestión de placa base \(BMC\) en el dispositivo de servicios SGF6112, SG6000 proporciona información de estado sobre el hardware y permite configurar los ajustes de SNMP y otras opciones para los dispositivos.' 
---
= Interfaz BMC: Descripción general (SGF6112, SG6000, SG100 y SG1000)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La interfaz de usuario del controlador de gestión de placa base (BMC) en el dispositivo de servicios SGF6112, SG6000 o proporciona información de estado sobre el hardware y permite configurar los ajustes de SNMP y otras opciones para los dispositivos.

Utilice los siguientes procedimientos en esta sección para configurar BMC al instalar el dispositivo:

* Cambie la contraseña raíz de la interfaz de BMC
* Establezca la dirección IP para el puerto de administración de BMC
* Acceda a la interfaz de BMC
* Configure los ajustes de SNMP
* Configurar notificaciones por correo electrónico y alertas



NOTE: Si el dispositivo ya se ha instalado en un grid y está ejecutando el software StorageGRID, consulte los siguientes procedimientos para ver un mecanismo alternativo para la configuración de BMC.
