---
permalink: installconfig/gathering-installation-information-sg5700.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, install, information, site, pre-install, preparing, prepare, preinstall, info, preparation 
summary: En las tablas, registre la información necesaria para cada red que conecte al dispositivo. Estos valores son necesarios para instalar y configurar el hardware. 
---
= Reunir información de instalación (SG5700)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En las tablas, registre la información necesaria para cada red que conecte al dispositivo. Estos valores son necesarios para instalar y configurar el hardware.


TIP: En lugar de utilizar las tablas, utilice el libro de trabajo proporcionado con ConfigBuilder. El uso del libro de trabajo de ConfigBuilder permite cargar información del sistema y generar un archivo JSON para completar automáticamente algunos pasos de configuración en el instalador de dispositivos de StorageGRID. Consulte link:automating-appliance-installation-and-configuration.html["Automatice la instalación y configuración de los dispositivos"].



== La información necesaria para conectarse a System Manager de SANtricity en la controladora E2800

Se conecta la controladora de la serie E2800 a la red de gestión que se utilizará para SANtricity System Manager.

[cols="2a,1a"]
|===
| Información necesaria | Su valor 


 a| 
El puerto del switch Ethernet se conectará al puerto de gestión 1
 a| 



 a| 
Dirección MAC del puerto de gestión 1 (impreso en una etiqueta cerca del puerto P1)
 a| 



 a| 
Dirección IP asignada por DHCP para el puerto de gestión 1, si está disponible después de encenderse

*Nota:* Si la red que va a conectar al controlador E2800 incluye un servidor DHCP, el administrador de red puede utilizar la dirección MAC para determinar la dirección IP asignada por el servidor DHCP.
 a| 



 a| 
Velocidad y modo doble

*Nota:* debe asegurarse de que el conmutador Ethernet de la red de administración de SANtricity System Manager está establecido en Negotiate automático.
 a| 
Debe ser:

* Autonegociar (predeterminado)




 a| 
Formato de dirección IP
 a| 
Elija una opción:

* IPv4
* IPv6




 a| 
Dirección IP estática que planea usar para el dispositivo en la red de gestión
 a| 
Para IPv4:

* Dirección IPv4:
* Máscara de subred:
* Puerta de enlace:


Para IPv6:

* Dirección IPv6:
* Dirección IP enrutable:
* Dirección IP del enrutador de la controladora E2800:


|===


== Información necesaria para conectar el controlador E5700SG a la red de administración

La red de administración de StorageGRID es una red opcional que se utiliza para la administración y el mantenimiento del sistema. El dispositivo se conecta a la red de administrador mediante los puertos de gestión de 1-GbE en la controladora E5700SG.

[cols="2a,1a"]
|===
| Información necesaria | Su valor 


 a| 
Red de administrador habilitada
 a| 
Elija una opción:

* No
* Sí (predeterminado)




 a| 
Modo de enlace de red
 a| 
Elija una opción:

* Independiente
* Copia de seguridad activa




 a| 
Puerto del switch para el puerto 1
 a| 



 a| 
Puerto del switch para el puerto 2 (únicamente modo de enlace de red Active-Backup)
 a| 



 a| 
Dirección IP asignada por DHCP para el puerto de gestión 1, si está disponible después de encenderse

*Nota:* Si la red Admin incluye un servidor DHCP, el controlador E5700SG muestra la dirección IP asignada por DHCP en su pantalla de siete segmentos después de que se inicie. También puede determinar la dirección IP asignada por DHCP utilizando la dirección MAC para buscar la IP asignada.
 a| 
* Dirección IPv4 (CIDR):
* Puerta de enlace:




 a| 
Dirección IP estática que piensa usar para el nodo de almacenamiento del dispositivo en la red de administración

*Nota:* Si su red no tiene una puerta de enlace, especifique la misma dirección IPv4 estática para la puerta de enlace.
 a| 
* Dirección IPv4 (CIDR):
* Puerta de enlace:




 a| 
Subredes de red de administración (CIDR)
 a| 

|===


== La información necesaria para conectar y configurar puertos 10/25-GbE en la controladora E5700SG

Los cuatro puertos 10/25-GbE del controlador E5700SG se conectan a la red de grid y la red de cliente de StorageGRID.


NOTE: Consulte link:port-bond-modes-for-e5700sg-controller-ports.html["Modos de enlace de puertos (controladora E5700SG)"].

[cols="2a,1a"]
|===
| Información necesaria | Su valor 


 a| 
Velocidad de enlace

*Nota:* Si selecciona 25 GbE, instale SPF28 transceptores. No se admite la autonegociación, por lo que también debe configurar los puertos y los switches conectados para 25GbE.
 a| 
Elija una opción:

* 10 GbE (predeterminado)
* 25 GbE




 a| 
Modo de enlace de puerto
 a| 
Elija una opción:

* Fijo (predeterminado)
* Agregado




 a| 
Puerto del switch para el puerto 1 (red cliente)
 a| 



 a| 
Puerto del switch para el puerto 2 (red de cuadrícula)
 a| 



 a| 
Puerto del switch para el puerto 3 (red cliente)
 a| 



 a| 
Puerto del switch para el puerto 4 (red Grid)
 a| 

|===


== Información necesaria para conectar el controlador E5700SG a Grid Network

Grid Network para StorageGRID es una red necesaria que se utiliza para todo el tráfico interno de StorageGRID. El dispositivo se conecta a la red Grid mediante los puertos 10/25-GbE en la controladora E5700SG.


NOTE: Consulte link:port-bond-modes-for-e5700sg-controller-ports.html["Modos de enlace de puertos (controladora E5700SG)"].

[cols="2a,1a"]
|===
| Información necesaria | Su valor 


 a| 
Modo de enlace de red
 a| 
Elija una opción:

* Active-Backup (predeterminado)
* LACP (802.3ad)




 a| 
Etiquetado VLAN habilitado
 a| 
Elija una opción:

* No (predeterminado)
* Sí




 a| 
Etiqueta de VLAN (si el etiquetado de VLAN está habilitado)
 a| 
Introduzca un valor entre 0 y 4095:



 a| 
Dirección IP asignada por DHCP para la red de cuadrícula, si está disponible después del encendido

*Nota:* Si Grid Network incluye un servidor DHCP, el controlador E5700SG muestra la dirección IP asignada por DHCP para la Red de cuadrícula en su pantalla de siete segmentos después de que se inicie.
 a| 
* Dirección IPv4 (CIDR):
* Puerta de enlace:




 a| 
Dirección IP estática que tiene previsto usar para el nodo de almacenamiento del dispositivo en la red de grid

*Nota:* Si su red no tiene una puerta de enlace, especifique la misma dirección IPv4 estática para la puerta de enlace.
 a| 
* Dirección IPv4 (CIDR):
* Puerta de enlace:




 a| 
Subredes de red de cuadrícula (CIDR)

*Nota:* Si la red de cliente no está activada, la ruta predeterminada del controlador utilizará la puerta de enlace especificada aquí.
 a| 

|===


== Información necesaria para conectar el controlador E5700SG a la red cliente

La red de cliente para StorageGRID es una red opcional que se suele utilizar para proporcionar acceso al protocolo de cliente al grid. El dispositivo se conecta a la red cliente mediante los puertos 10/25-GbE en la controladora E5700SG.


NOTE: Consulte link:port-bond-modes-for-e5700sg-controller-ports.html["Modos de enlace de puertos (controladora E5700SG)"].

[cols="2a,1a"]
|===
| Información necesaria | Su valor 


 a| 
Red de cliente habilitada
 a| 
Elija una opción:

* No (predeterminado)
* Sí




 a| 
Modo de enlace de red
 a| 
Elija una opción:

* Active-Backup (predeterminado)
* LACP (802.3ad)




 a| 
Etiquetado VLAN habilitado
 a| 
Elija una opción:

* No (predeterminado)
* Sí




 a| 
Etiqueta de VLAN

(Si el etiquetado de VLAN está habilitado)
 a| 
Introduzca un valor entre 0 y 4095:



 a| 
Dirección IP asignada por DHCP para la red cliente, si está disponible después del encendido
 a| 
* Dirección IPv4 (CIDR):
* Puerta de enlace:




 a| 
Dirección IP estática que tiene previsto usar para el nodo de almacenamiento del dispositivo en la red cliente

*Nota:* Si la red de cliente está activada, la ruta predeterminada del controlador utilizará la puerta de enlace especificada aquí.
 a| 
* Dirección IPv4 (CIDR):
* Puerta de enlace:


|===
.Información relacionada
* link:sg5700-appliance-connections.html["Conexiones de red (SG5700)"]
* link:port-bond-modes-for-e5700sg-controller-ports.html["Modos de enlace de puertos (controladora E5700SG)"]
* link:configuring-hardware.html["Configurar hardware (SG5700)"]

