---
permalink: installconfig/troubleshooting-connection-issues-sgf6112.html 
sidebar: sidebar 
keywords: storagegrid, sgf6112, sg6100, troubleshoot, troubleshooting, connection 
summary: Si tiene problemas de conexión durante la instalación del dispositivo StorageGRID, debe ejecutar los pasos de acción correctiva indicados. 
---
= Solución de problemas de conexión (SGF6112)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si tiene problemas de conexión durante la instalación del dispositivo StorageGRID, debe ejecutar los pasos de acción correctiva indicados.



== No se puede conectar al dispositivo

Si no puede conectarse a la aplicación de servicios, es posible que haya un problema de red o que la instalación de hardware no se haya completado correctamente.

.Pasos
. Intente hacer ping al dispositivo con la dirección IP del dispositivo : +
`*ping _appliance_IP_*`
. Si no recibe respuesta del ping, confirme que está utilizando la dirección IP correcta.
+
Puede utilizar la dirección IP del dispositivo en la red de grid, la red de administración o la red de cliente.

. Si la dirección IP es correcta, compruebe el cableado del dispositivo, los transceptores QSFP o SFP y la configuración de red.
. Si dispone de acceso físico al dispositivo, puede utilizar una conexión directa a la IP local permanente de enlace `169.254.0.1` para comprobar la configuración de redes de la controladora y actualizarla si es necesario. Para obtener instrucciones detalladas, consulte el paso 2 de la link:accessing-storagegrid-appliance-installer.html["Acceda al instalador de dispositivos de StorageGRID"].
+
Si esto no se resuelve el problema, póngase en contacto con el soporte técnico.

. Si el ping se ha realizado correctamente, abra un explorador Web.
. Introduzca la URL para el instalador de dispositivos de StorageGRID: +
`*https://_appliances_controller_IP_:8443*`
+
Aparece la página de inicio.


