---
permalink: installconfig/viewing-error-codes-for-sg6000-cn-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, error codes, errors, error, codes, sg6000-cn 
summary: Si se produce un error de hardware cuando se inicia el controlador SG6000-CN, el BMC registra un código de error. Según sea necesario, puede ver estos códigos de error mediante la interfaz del BMC y, a continuación, trabajar con el soporte técnico para resolver el problema. 
---
= Ver códigos de error (controlador SG6000-CN)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si se produce un error de hardware cuando se inicia el controlador SG6000-CN, el BMC registra un código de error. Según sea necesario, puede ver estos códigos de error mediante la interfaz del BMC y, a continuación, trabajar con el soporte técnico para resolver el problema.

.Antes de empezar
* Sabe cómo acceder al panel de BMC.


.Pasos
. En el panel de control del BMC, seleccione *Código POST del BIOS*.
. Revise la información que se muestra para el código actual y el código anterior.
+
Si se muestra alguno de los siguientes códigos de error, trabaje con el soporte técnico para resolver el problema.

+
[cols="1a,3a"]
|===
| Codificación | Lo que indica 


 a| 
0x0e
 a| 
No se ha encontrado el microcódigo



 a| 
0x0F
 a| 
No se ha cargado el microcódigo



 a| 
0x50
 a| 
Error de inicialización de la memoria. Tipo de memoria no válido o velocidad de memoria incompatible.



 a| 
0x51
 a| 
Error de inicialización de la memoria. Error en la lectura del SPD.



 a| 
0x52
 a| 
Error de inicialización de la memoria. Tamaño de memoria no válido o los módulos de memoria no coinciden.



 a| 
0x53
 a| 
Error de inicialización de la memoria. No se detectó memoria utilizable.



 a| 
0x54
 a| 
Error de inicialización de memoria no especificada



 a| 
0x55
 a| 
Memoria no instalada



 a| 
0x56
 a| 
Tipo o velocidad de CPU no válida



 a| 
0x57
 a| 
Discordancia de CPU



 a| 
0x58
 a| 
Fallo de la autoprueba de CPU o posible error de caché de CPU



 a| 
0x59
 a| 
No se ha encontrado el micro-código de la CPU, o la actualización del micro-código ha fallado



 a| 
0x5A
 a| 
Error interno de CPU



 a| 
0x5b
 a| 
Restablecer PPI no está disponible



 a| 
0x5c
 a| 
Fallo de autocomprobación PEI Phase BMC



 a| 
0xD0
 a| 
Error de inicialización de la CPU



 a| 
0xD1
 a| 
Error de inicialización del puente norte



 a| 
0xD2
 a| 
Error de inicialización del puente sur



 a| 
0xd3
 a| 
Algunos protocolos de arquitectura no están disponibles



 a| 
0xD4
 a| 
Error de asignación de recursos PCI. De recursos.



 a| 
0xD5
 a| 
No hay espacio para la ROM de opción heredada



 a| 
0xD6
 a| 
No se han encontrado dispositivos de salida de consola



 a| 
0xD7
 a| 
No se han encontrado dispositivos de entrada de consola



 a| 
0xD8
 a| 
Contraseña no válida



 a| 
0xD9
 a| 
Error al cargar la opción de arranque (LoadImage devolvió un error)



 a| 
0xDA
 a| 
Error en la opción de inicio (error de Startimage devuelto)



 a| 
0xDB
 a| 
Error en la actualización de Flash



 a| 
0xDC
 a| 
El protocolo de restablecimiento no está disponible



 a| 
0xDD
 a| 
Error de autoprueba de DXE Phase BMC



 a| 
0xE8
 a| 
MRC: ERR_NO_MEMORY



 a| 
0xE9
 a| 
MRC: ERR_LT_LOCK



 a| 
0xEA
 a| 
MRC: ERR_DDR_INIT



 a| 
0xEB
 a| 
MRC: ERR_MEM_TEST



 a| 
0xEC
 a| 
MRC: ERR_VENDOR_SPECIFIC



 a| 
0xED
 a| 
MRC: ERR_DIMM_COMPAT



 a| 
0xEE
 a| 
MRC: ERR_MRC_COMPATIBILIDAD



 a| 
0xEF
 a| 
MRC: ERR_MRC_STRUCT



 a| 
0xF0
 a| 
MRC: ERR_SET_VDD



 a| 
0xF1
 a| 
MRC: ERR_IOT_MEM_BUFFER



 a| 
0xF2
 a| 
MRC: ERR_RC_INTERNAL



 a| 
0xF3
 a| 
MRC: ERR_INVALID_REG_ACCESS



 a| 
0xF4
 a| 
MRC: ERR_SET_MC_FREQ



 a| 
0xF5
 a| 
MRC: ERR_READ_MC_FREQ



 a| 
0x70
 a| 
MRC: ERR_DIMM_CHANNEL



 a| 
0x74
 a| 
MRC: ERR_BIST_CHECK



 a| 
0xF6
 a| 
MRC: ERR_SMBUS



 a| 
0xF7
 a| 
MRC: ERR_PCU



 a| 
0xF8
 a| 
MRC: ERR_NGN



 a| 
0xF9
 a| 
MRC: ERR_INTERLEAVE_FAILURE

|===

