---
permalink: network/appliance-nodes.html 
sidebar: sidebar 
keywords: networking for appliance, port bond mode 
summary: Puede configurar los puertos de red en dispositivos StorageGRID para utilizar los modos de enlace de puertos que cumplan con los requisitos de rendimiento, redundancia y conmutación al respaldo. 
---
= Nodos del dispositivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar los puertos de red en dispositivos StorageGRID para utilizar los modos de enlace de puertos que cumplan con los requisitos de rendimiento, redundancia y conmutación al respaldo.

Los puertos 10/25-GbE de los dispositivos StorageGRID se pueden configurar en modo de enlace fijo o agregado para las conexiones a la red Grid y a la red de clientes.

Los puertos de red administrador de 1 GbE se pueden configurar en modo independiente o activo-Backup para las conexiones a la red administrativa.

Consulte la información sobre los modos de enlace de puertos para su dispositivo:

* link:../installconfig/port-bond-modes-for-sgf6112.html["Modos de enlace de puertos (SGF6112)"]
* link:../installconfig/port-bond-modes-for-sg6000-cn-controller.html["Modos de enlace de puertos (controladora SG6000-CN)"]
* link:../installconfig/port-bond-modes-for-e5700sg-controller-ports.html["Modos de enlace de puertos (controladora E5700SG)"]
* link:../installconfig/port-bond-modes-for-sg100-and-sg1000.html["Modos de enlace de puertos (SG100 y SG1000)"]

