---
permalink: tenant/tenant-management-permissions.html 
sidebar: sidebar 
keywords: tenant management permissions 
summary: Antes de crear un grupo de arrendatarios, tenga en cuenta qué permisos desea asignar a ese grupo. Los permisos de administración de inquilinos determinan qué tareas pueden realizar los usuarios con el Administrador de inquilinos o la API de gestión de inquilinos. Un usuario puede pertenecer a uno o más grupos. Los permisos son acumulativos si un usuario pertenece a varios grupos. 
---
= Permisos de gestión de inquilinos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de crear un grupo de arrendatarios, tenga en cuenta qué permisos desea asignar a ese grupo. Los permisos de administración de inquilinos determinan qué tareas pueden realizar los usuarios con el Administrador de inquilinos o la API de gestión de inquilinos. Un usuario puede pertenecer a uno o más grupos. Los permisos son acumulativos si un usuario pertenece a varios grupos.

Para iniciar sesión en el Administrador de arrendatarios o utilizar la API de administración de arrendatarios, los usuarios deben pertenecer a un grupo que tenga al menos un permiso. Todos los usuarios que puedan iniciar sesión pueden realizar las siguientes tareas:

* Vea la consola
* Cambiar su propia contraseña (para usuarios locales)


Para todos los permisos, la configuración del modo de acceso del grupo determina si los usuarios pueden cambiar la configuración y realizar operaciones o si sólo pueden ver la configuración y las características relacionadas.


NOTE: Si un usuario pertenece a varios grupos y cualquier grupo está establecido en sólo lectura, el usuario tendrá acceso de sólo lectura a todos los ajustes y características seleccionados.

Puede asignar los siguientes permisos a un grupo. Tenga en cuenta que los inquilinos de S3 y los inquilinos de Swift tienen diferentes permisos de grupo.

[cols="1a,3a"]
|===
| Permiso | Descripción 


 a| 
Acceso raíz
 a| 
Proporciona acceso completo al administrador de inquilinos y a la API de gestión de inquilinos.

*Nota:* Los usuarios de Swift deben tener permiso de acceso root para iniciar sesión en la cuenta del inquilino.



 a| 
Administrador
 a| 
Solo para inquilinos Swift. Proporciona acceso completo a los contenedores y objetos de Swift para esta cuenta de inquilino

*Nota:* los usuarios de Swift deben tener el permiso de Administrador de Swift para realizar cualquier operación con la API de REST de Swift.



 a| 
Gestione sus propias credenciales de S3
 a| 
Permite a los usuarios crear y eliminar sus propias claves de acceso S3. Los usuarios que no tienen este permiso no ven la opción de menú *STORAGE (S3)* > *My S3 access keys*.



 a| 
Gestionar todos los cucharones
 a| 
* Inquilinos S3: Permite a los usuarios usar el administrador de inquilinos y la API de gestión de inquilinos para crear y eliminar bloques S3, así como para gestionar la configuración de todos los bloques de S3 de la cuenta del inquilino, independientemente de las políticas de grupo o bloque de S3.
+
Los usuarios que no tienen este permiso no ven la opción de menú *Buckets*.

* Inquilinos Swift: Permite a los usuarios de Swift controlar el nivel de coherencia de los contenedores Swift mediante la API de gestión de inquilinos.


*Nota:* Solo puede asignar el permiso Administrar todos los cubos a grupos Swift desde la API de administración de inquilinos. No puede asignar este permiso a grupos Swift mediante el administrador de inquilinos.



 a| 
Gestionar puntos finales
 a| 
Permite a los usuarios utilizar el Gestor de inquilinos o la API de gestión de inquilinos para crear o editar puntos finales de servicio de plataforma, que se utilizan como destino para los servicios de plataforma de StorageGRID.

Los usuarios que no tienen este permiso no ven la opción de menú *Platform services endpoints*.



 a| 
Gestionar objetos con S3 Console
 a| 
Cuando se combina con el permiso Gestionar todos los depósitos, permite a los usuarios acceder a la Consola Experimental S3 desde la página Buckets. Los usuarios que tienen este permiso pero que no tienen el permiso Administrar todos los depósitos pueden navegar directamente a la Consola Experimental S3.

|===