---
permalink: tenant/tenant-management-api-versioning.html 
sidebar: sidebar 
keywords: tenant management api version 
summary: La API de gestión de inquilinos utiliza versiones para dar cabida a actualizaciones no disruptivas. 
---
= Creación de versiones de la API de gestión de inquilinos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La API de gestión de inquilinos utiliza versiones para dar cabida a actualizaciones no disruptivas.

Por ejemplo, esta URL de solicitud especifica la versión 3 de la API.

`https://_hostname_or_ip_address_/api/v3/authorize`

La versión principal de la API de administración de inquilinos se salta cuando se realizan cambios que son _no compatibles_ con versiones anteriores. La versión secundaria de la API de gestión de inquilinos se salta cuando se realizan cambios que son compatibles con versiones anteriores. Los cambios compatibles incluyen la adición de nuevos extremos o nuevas propiedades. En el ejemplo siguiente se muestra cómo la versión de API se bONTAP en función del tipo de cambios realizados.

[cols="2a,1a,1a"]
|===
| Tipo de cambio en la API | Versión anterior | Nueva versión 


 a| 
Compatible con versiones anteriores
 a| 
2.1
 a| 
2.2



 a| 
No es compatible con versiones anteriores
 a| 
2.1
 a| 
3.0

|===
Cuando el software StorageGRID se instala por primera vez, solo se habilita la versión más reciente de la API de gestión de inquilinos. Sin embargo, cuando StorageGRID se actualiza a una versión de función nueva, sigue teniendo acceso a la versión de API anterior para al menos una versión de la función StorageGRID.

Las solicitudes obsoletas se marcan como obsoletas de las siguientes formas:

* El encabezado de la respuesta es "Dedeprecated: True"
* El cuerpo de respuesta JSON incluye "obsoleto": TRUE




== Determine qué versiones de API son compatibles en la versión actual

Utilice la siguiente solicitud de API para devolver una lista de las versiones principales de API admitidas:

[listing]
----
GET https://{{IP-Address}}/api/versions
{
  "responseTime": "2019-01-10T20:41:00.845Z",
  "status": "success",
  "apiVersion": "3.0",
  "data": [
    2,
    3
  ]
}
----


== Especifique la versión de API para la solicitud

Puede especificar la versión de API mediante un parámetro path (`/api/v3`) o un encabezado (`Api-Version: 3`). Si proporciona ambos valores, el valor de encabezado anula el valor de ruta de acceso.

`curl \https://<IP-Address>/api/v3/grid/accounts`

`curl -H "Api-Version: 3" \https://<IP-Address>/api/grid/accounts`
