---
permalink: vmware/planning-and-preparation.html 
sidebar: sidebar 
keywords: how to plan before installation 
summary: Antes de implementar nodos de grid y configurar la cuadrícula de StorageGRID, debe estar familiarizado con los pasos y los requisitos para completar el procedimiento. 
---
= Antes de instalar (VMware)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de implementar nodos de grid y configurar la cuadrícula de StorageGRID, debe estar familiarizado con los pasos y los requisitos para completar el procedimiento.

Los procedimientos de puesta en marcha y configuración de StorageGRID dan por sentado que conoce la arquitectura y la funcionalidad operativa del sistema StorageGRID.

Puede implementar un solo sitio o varios sitios a la vez; sin embargo, todos los sitios deben cumplir con el requisito mínimo de tener al menos tres nodos de almacenamiento.

Antes de iniciar el procedimiento de implementación y de configuración de grid del nodo, debe:

* Planifique la implementación de StorageGRID.
* Instale, conecte y configure todo el hardware necesario, incluidos los dispositivos StorageGRID, según las especificaciones.
+

IMPORTANT: Si la instalación de StorageGRID no utilizará nodos de almacenamiento del dispositivo StorageGRID (hardware), debe usar almacenamiento RAID de hardware con caché de escritura respaldada por batería (BBWC). StorageGRID no admite el uso de redes de área de almacenamiento virtuales (VSAN), RAID de software ni ninguna protección RAID.

+

NOTE: Las instrucciones de instalación e integración específicas del hardware no se incluyen en el procedimiento de instalación de StorageGRID. Para saber cómo instalar dispositivos StorageGRID, consulte link:../installconfig/index.html["Instale el hardware del dispositivo"].

* Comprenda el link:../network/index.html["opciones de red disponibles y cómo se debe implementar cada opción de red en los nodos de grid"].
* Recopile toda la información de la red con antelación. A menos que utilice DHCP, recopile las direcciones IP para asignar a cada nodo de grid y las direcciones IP de los servidores DNS y NTP que se usarán.
* Decida qué herramientas de implementación y configuración disponibles desea utilizar.

