---
permalink: admin/grid-management-api-versioning.html 
sidebar: sidebar 
keywords: grid management api, api versioning 
summary: La API de gestión de grid utiliza versiones para permitir actualizaciones sin interrupciones. 
---
= Creación de versiones de la API de gestión de grid
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La API de gestión de grid utiliza versiones para permitir actualizaciones sin interrupciones.

Por ejemplo, esta URL de solicitud especifica la versión 3 de la API.

`https://_hostname_or_ip_address_/api/v3/authorize`

La versión principal de la API de administración de arrendatarios se bONTAP cuando se realizan cambios que son *_no compatibles_* con versiones anteriores. La versión menor de la API de administración de arrendatarios se bONTAP cuando se hacen cambios que *_are sea compatible_* con versiones anteriores. Los cambios compatibles incluyen la adición de nuevos extremos o nuevas propiedades. En el ejemplo siguiente se muestra cómo la versión de API se bONTAP en función del tipo de cambios realizados.

[cols="1a,1a,1a"]
|===
| Tipo de cambio en la API | Versión anterior | Nueva versión 


 a| 
Compatible con versiones anteriores
 a| 
2.1
 a| 
2.2



 a| 
No es compatible con versiones anteriores
 a| 
2.1
 a| 
3.0

|===
Al instalar el software StorageGRID por primera vez, sólo se activa la versión más reciente de la API de gestión de grid. Sin embargo, cuando actualice a una versión de función nueva de StorageGRID, seguirá teniendo acceso a la versión de API anterior para al menos una versión de función de StorageGRID.


NOTE: Puede utilizar la API de gestión de grid para configurar las versiones compatibles. Consulte la sección «'config'» de la documentación de API de Swagger para obtener más información. Debe desactivar la compatibilidad con la versión anterior después de actualizar todos los clientes de la API de Grid Management para que utilicen la versión más reciente.

Las solicitudes obsoletas se marcan como obsoletas de las siguientes formas:

* El encabezado de la respuesta es "Dedeprecated: True"
* El cuerpo de respuesta JSON incluye "obsoleto": TRUE
* Se agrega una advertencia obsoleta a nms.log. Por ejemplo:
+
[listing]
----
Received call to deprecated v1 API at POST "/api/v1/authorize"
----




== Determine qué versiones de API son compatibles con la versión actual

Utilice la siguiente solicitud de API para devolver una lista de las versiones principales de API admitidas:

[listing]
----
GET https://{{IP-Address}}/api/versions
{
  "responseTime": "2019-01-10T20:41:00.845Z",
  "status": "success",
  "apiVersion": "3.0",
  "data": [
    2,
    3
  ]
}
----


== Especifique una versión API para una solicitud

Puede especificar la versión de API mediante un parámetro path (`/api/v3`) o un encabezado (`Api-Version: 3`). Si proporciona ambos valores, el valor de encabezado anula el valor de ruta de acceso.

[listing]
----
curl https://[IP-Address]/api/v3/grid/accounts

curl -H "Api-Version: 3" https://[IP-Address]/api/grid/accounts
----