---
permalink: admin/what-admin-node-is.html 
sidebar: sidebar 
keywords: admin nodes 
summary: Los nodos de administración, que proporcionan servicios de gestión como configuración, supervisión y registro del sistema. Cada grid debe tener un nodo de administrador primario y puede tener cualquier cantidad de nodos de administrador no primarios por motivos de redundancia. 
---
= ¿Qué es un nodo de administración?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los nodos de administración, que proporcionan servicios de gestión como configuración, supervisión y registro del sistema. Cada grid debe tener un nodo de administrador primario y puede tener cualquier cantidad de nodos de administrador no primarios por motivos de redundancia.

Cuando inicia sesión en el administrador de grid o en el administrador de inquilinos, se conecta a un nodo de administración. Puede conectarse a cualquier nodo de administrador y cada nodo de administrador muestra una vista similar del sistema StorageGRID. Sin embargo, se deben realizar los procedimientos de mantenimiento usando el nodo de administración principal.

Los nodos de administración también se pueden usar para equilibrar la carga del tráfico de clientes S3 y Swift.



== ¿Cuál es el remitente preferido

Si la implementación de StorageGRID incluye varios nodos de administración, el nodo de administración principal es el remitente preferido para las notificaciones de alertas, los mensajes de AutoSupport, las capturas e informes SNMP y las notificaciones de alarmas heredadas.

En operaciones normales del sistema, solo el remitente preferido envía notificaciones. Sin embargo, el resto de los nodos de administración supervisan el remitente preferido. Si se detecta un problema, otros nodos de administración actúan como _remitentes en espera_.

Es posible que se envíen varias notificaciones en los siguientes casos:

* Si los nodos de administración pasan a ser “indistribuidos” entre sí, tanto el remitente preferido como los remitentes en espera intentarán enviar notificaciones, y es posible que se reciban varias copias de las notificaciones.
* Si el remitente en espera detecta problemas con el remitente preferido y comienza a enviar notificaciones, es posible que el remitente preferido recupere su capacidad para enviar notificaciones. Si esto ocurre, es posible que se envíen notificaciones duplicadas. El remitente en espera dejará de enviar notificaciones cuando ya no detecte errores en el remitente preferido.
+

NOTE: Cuando prueba los mensajes de AutoSupport, todos los nodos de administrador envían el correo electrónico de prueba. Cuando prueba las notificaciones de alerta, debe iniciar sesión en cada nodo de administrador para verificar la conectividad.





== Servicios primarios para nodos de administración

En la siguiente tabla se muestran los servicios principales de los nodos de administrador; sin embargo, esta tabla no enumera todos los servicios de nodo.

[cols="1a,2a"]
|===
| Servicio | Función de la tecla 


 a| 
Sistema de gestión de auditorías (AMS)
 a| 
Realiza un seguimiento de la actividad y los eventos del sistema.



 a| 
Nodo de gestión de configuraciones (CMN)
 a| 
Gestiona la configuración en todo el sistema. Solo nodo de administrador principal.



 a| 
Interfaz de programas de aplicaciones de gestión (API de gestión)
 a| 
Procesa las solicitudes de la API de gestión de grid y la API de gestión de inquilinos.



 a| 
Alta disponibilidad
 a| 
Administra direcciones IP virtuales de alta disponibilidad para grupos de nodos de administración y nodos de puerta de enlace.

*Nota:* este servicio también se encuentra en los nodos Gateway.



 a| 
Equilibrador de carga
 a| 
Proporciona el equilibrio de carga del tráfico de S3 y Swift desde los clientes a los nodos de almacenamiento.

*Nota:* este servicio también se encuentra en los nodos Gateway.



 a| 
Sistema de gestión de redes (NMS)
 a| 
Proporciona funcionalidad para Grid Manager.



 a| 
Prometheus
 a| 
Recopila y almacena métricas de series temporales de los servicios en todos los nodos.



 a| 
Monitor de estado del servidor (SSM)
 a| 
Supervisa el sistema operativo y el hardware subyacente.

|===