---
permalink: s3/get-object.html 
sidebar: sidebar 
keywords: get object 
summary: Puede usar la solicitud GET Object de S3 para recuperar un objeto de un bloque de S3. 
---
= OBTENER objeto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar la solicitud GET Object de S3 para recuperar un objeto de un bloque de S3.



== OBJETOS GET y objetos de varias partes

Puede utilizar el `partNumber` parámetro de solicitud para recuperar una parte específica de un objeto de varias partes o segmentado. La `x-amz-mp-parts-count` el elemento de respuesta indica cuántas partes tiene el objeto.

Puede ajustar `partNumber` a 1 para objetos segmentados/multipartes y no segmentados/no multipartes; sin embargo, la `x-amz-mp-parts-count` el elemento de respuesta sólo se devuelve para objetos segmentados o multipartes.



== Caracteres UTF-8 en los metadatos de usuario

StorageGRID no analiza ni interpreta caracteres UTF-8 escapados en los metadatos definidos por el usuario. Las solicitudes GET para un objeto con caracteres UTF-8 que se han escapado en los metadatos definidos por el usuario no devuelven el `x-amz-missing-meta` encabezado si el nombre o valor de clave incluye caracteres no imprimibles.



== Encabezado de solicitud no compatible

El siguiente encabezado de solicitud no es compatible y devuelve `XNotImplemented`:

* `x-amz-website-redirect-location`




== Creación de versiones

Si es un `versionId` no se especifica el subrecurso, la operación busca la versión más reciente del objeto en un bloque con versiones. Si la versión actual del objeto es un marcador de borrado, se devuelve el estado "'no encontrado'" con la `x-amz-delete-marker` encabezado de respuesta establecido en `true`.



== Solicitar encabezados para el cifrado del servidor con claves de cifrado proporcionadas por el cliente (SSE-C)

Utilice los tres encabezados si el objeto está cifrado con una clave única que ha proporcionado.

* `x-amz-server-side-encryption-customer-algorithm`: Especificar `AES256`.
* `x-amz-server-side-encryption-customer-key`: Especifique la clave de cifrado del objeto.
* `x-amz-server-side-encryption-customer-key-MD5`: Especifique el resumen MD5 de la clave de cifrado del objeto.



IMPORTANT: Las claves de cifrado que proporcione no se almacenan nunca. Si pierde una clave de cifrado, perderá el objeto correspondiente. Antes de utilizar las claves proporcionadas por el cliente para proteger los datos de objetos, revise las consideraciones que se deben tener en link:using-server-side-encryption.html["Usar cifrado del servidor"].



== Comportamiento de OBTENER objeto para objetos de pool de almacenamiento en cloud

Si un objeto se ha almacenado en un link:../ilm/what-cloud-storage-pool-is.html["Pool de almacenamiento en cloud"], El comportamiento de una solicitud GET Object depende del estado del objeto. Consulte link:head-object.html["OBJETO HEAD"] para obtener más detalles.


NOTE: Si un objeto está almacenado en un Cloud Storage Pool y existen también una o varias copias del objeto en el grid, GET Object Requests intentará recuperar datos del grid, antes de recuperarlos del Cloud Storage Pool.

[cols="1a,1a"]
|===
| Estado del objeto | Comportamiento DE GET Object 


 a| 
Objeto ingerido en StorageGRID pero aún no evaluado por ILM, u objeto almacenado en un pool de almacenamiento tradicional o utilizando código de borrado
 a| 
`200 OK`

Se recupera una copia del objeto.



 a| 
Objeto en el pool de almacenamiento en cloud pero todavía no ha realizado la transición a un estado no recuperable
 a| 
`200 OK`

Se recupera una copia del objeto.



 a| 
Objeto que ha pasado a un estado no recuperable
 a| 
`403 Forbidden`, `InvalidObjectState`

Utilice un link:post-object-restore.html["Restauración DE objetos posterior"] solicitud para restaurar el objeto a un estado recuperable.



 a| 
Objeto en proceso de restauración a partir de un estado no recuperable
 a| 
`403 Forbidden`, `InvalidObjectState`

Espere a que se complete la solicitud DE restauración DE objeto POSTERIOR.



 a| 
Objeto completamente restaurado en el pool de almacenamiento en cloud
 a| 
`200 OK`

Se recupera una copia del objeto.

|===


=== Objetos de varias partes o segmentados en un pool de almacenamiento en nube

Si cargó un objeto con varias partes o StorageGRID dividió un objeto grande en segmentos, StorageGRID determina si el objeto está disponible en el pool de almacenamiento en cloud al muestrear un subconjunto de las partes o segmentos del objeto. En algunos casos, es posible que UNA solicitud GET Object devuelva incorrectamente `200 OK` cuando algunas partes del objeto ya se han trasladado a un estado no recuperable o cuando algunas partes del objeto aún no se han restaurado.

En estos casos:

* La solicitud GET Object puede devolver algunos datos pero detenerse a mitad de camino a través de la transferencia.
* Una petición GET Object posterior podría devolver `403 Forbidden`.




== OBTENGA la replicación de objetos y entre grid

Si está utilizando link:../admin/grid-federation-overview.html["federación de grid"] y.. link:../tenant/grid-federation-manage-cross-grid-replication.html["replicación entre grid"] Está activado para un depósito, el cliente S3 puede verificar el estado de replicación de un objeto emitiendo una solicitud GET Object. La respuesta incluye los recursos específicos de StorageGRID `x-ntap-sg-cgr-replication-status` cabecera de respuesta, que tendrá uno de los siguientes valores:

[cols="1a,2a"]
|===
| Cuadrícula | Estado de replicación 


 a| 
Origen
 a| 
* *ÉXITO*: La replicación fue exitosa.
* *PENDIENTE*: El objeto aún no ha sido replicado.
* *FALLO*: La replicación falló con un fallo permanente. Un usuario debe resolver el error.




 a| 
Destino
 a| 
*REPLICA*: El objeto fue replicado desde la cuadrícula de origen.

|===

NOTE: StorageGRID no admite el `x-amz-replication-status` encabezado.

.Información relacionada
link:s3-operations-tracked-in-audit-logs.html["Se realizó un seguimiento de las operaciones de S3 en los registros de auditoría"]
