---
permalink: s3/operations-on-buckets.html 
sidebar: sidebar 
keywords: bucket, buckets, operations on buckets 
summary: El sistema StorageGRID admite un máximo de 1,000 bloques para cada cuenta de inquilino de S3. 
---
= Operaciones en bloques
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El sistema StorageGRID admite un máximo de 1,000 bloques para cada cuenta de inquilino de S3.

Las restricciones de nombre de bloque siguen las restricciones de región estándar de AWS EE.UU., pero debe restringirlas a las convenciones de nomenclatura DNS para admitir solicitudes virtuales de estilo hospedado de S3.

En la siguiente sección, se ofrece más información:

* https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html["Documentación de Amazon Web Services (AWS): Restricciones y limitaciones de buckets"^]
* link:../admin/configuring-s3-api-endpoint-domain-names.html["Configure los nombres de dominio de punto final S3"]


Las operaciones GET Bucket (List Objects) Y GET Bucket admiten los controles de coherencia de StorageGRID.

Puede comprobar si las actualizaciones a la hora del último acceso están habilitadas o deshabilitadas para grupos individuales.

En la siguiente tabla se describe cómo StorageGRID implementa operaciones de bloque de API DE REST de S3. Para realizar alguna de estas operaciones, se deben proporcionar las credenciales de acceso necesarias para la cuenta.

[cols="1a,3a"]
|===
| Funcionamiento | Implementación 


 a| 
ELIMINAR bloque
 a| 
Esta operación elimina el cucharón.



 a| 
ELIMINAR los cors de cucharón
 a| 
Esta operación elimina la configuración de CORS para el cucharón.



 a| 
DELETE Bucket Encryption
 a| 
Esta operación elimina el cifrado predeterminado del bloque. Los objetos cifrados existentes permanecen cifrados, pero todos los objetos nuevos agregados al depósito no están cifrados.



 a| 
ELIMINAR ciclo de vida de bloque
 a| 
Esta operación elimina la configuración del ciclo de vida del bloque. Consulte link:create-s3-lifecycle-configuration.html["Cree una configuración del ciclo de vida de S3"].



 a| 
ELIMINE la política de bloques
 a| 
Esta operación elimina la política asociada al bloque.



 a| 
DELETE Bucket replicación
 a| 
Esta operación elimina la configuración de replicación conectada al bloque.



 a| 
DELETE Bucket tagging
 a| 
Esta operación utiliza `tagging` subrecurso para quitar todas las etiquetas de un bloque.



 a| 
OBTENER bloque

(ListObjects)

(ListObjectsV2)
 a| 
Esta operación devuelve algunos o todos (hasta 1,000) de los objetos de un bloque. La clase de almacenamiento para los objetos puede tener cualquiera de dos valores, incluso si el objeto se ingirió con la `REDUCED_REDUNDANCY` opción de clase de almacenamiento:

* `STANDARD`, Que indica que el objeto se almacena en una agrupación de almacenamiento que consta de nodos de almacenamiento.
* `GLACIER`, Que indica que el objeto se ha movido al bloque externo especificado por el grupo de almacenamiento en la nube.


Si el bloque contiene un gran número de claves eliminadas que tienen el mismo prefijo, la respuesta podría incluir algunas `CommonPrefixes` que no contienen claves.



 a| 
OBTENGA las versiones DE objeto Bucket

(Versiones de ListObjectVersions)
 a| 
Con el acceso DE LECTURA en un bloque, esta operación con el `versions` subrecurso enumera los metadatos de todas las versiones de objetos del bloque.



 a| 
GET Bucket acl
 a| 
Esta operación devuelve una respuesta positiva y el ID, DisplayName y permiso del propietario del bloque, lo que indica que el propietario tiene acceso completo al bloque.



 a| 
OBTENGA los cors del cucharón
 a| 
Esta operación devuelve el `cors` configuración del bloque.



 a| 
OBTENGA el cifrado de bloque
 a| 
Esta operación devuelve la configuración de cifrado predeterminada del bloque.



 a| 
OBTENGA el ciclo de vida de la cuchara

(GetBucketLifecycleConfiguration)
 a| 
Esta operación devuelve la configuración del ciclo de vida del bloque. Consulte link:create-s3-lifecycle-configuration.html["Cree una configuración del ciclo de vida de S3"].



 a| 
OBTENER ubicación de bloque
 a| 
Esta operación devuelve la región que se estableció mediante el `LocationConstraint` Elemento de la solicitud PUT Bucket. Si la región del cucharón es `us-east-1`, se devuelve una cadena vacía para la región.



 a| 
OBTENGA la notificación DE BUCKET

(GetBucketNotificationConfiguration)
 a| 
Esta operación devuelve la configuración de notificación asociada al bloque.



 a| 
OBTENGA la política de bloques
 a| 
Esta operación devuelve la política asociada al bloque.



 a| 
OBTENGA la replicación de Bucket
 a| 
Esta operación devuelve la configuración de replicación asociada al bloque.



 a| 
GET Bucket tagging
 a| 
Esta operación utiliza `tagging` subrecurso para devolver todas las etiquetas de un bloque.



 a| 
OBTENGA el control de versiones de Bucket
 a| 
Esta implementación usa la `versioning` subrecurso para devolver el estado de control de versiones de un bloque.

* _Blank_: Nunca se ha activado el control de versiones (el cucharón es "'unversioned'")
* Activado: El control de versiones está activado
* Suspendido: El control de versiones se ha habilitado anteriormente y se ha suspendido




 a| 
OBTENER configuración de bloqueo de objeto
 a| 
Esta operación devuelve el modo de retención predeterminado de bloque y el período de retención predeterminado, si está configurado.

Consulte link:../s3/use-s3-api-for-s3-object-lock.html["Use la API REST DE S3 para configurar el bloqueo de objetos de S3"].



 a| 
Cubo DE CABEZA
 a| 
Esta operación determina si existe un bloque y tiene permiso para acceder a él.

Esta operación devuelve:

* `x-ntap-sg-bucket-id`: El UUID del bloque en formato UUID.
* `x-ntap-sg-trace-id`: El ID de traza único de la solicitud asociada.




 a| 
COLOQUE el cucharón
 a| 
Esta operación crea un nuevo bloque. Al crear la cuchara, se convierte en el propietario de la cuchara.

* Los nombres de los bloques deben cumplir con las siguientes reglas:
+
** Debe ser único en cada sistema StorageGRID (no solo dentro de la cuenta de inquilino).
** Debe ser compatible con DNS.
** Debe incluir al menos 3 y no más de 63 caracteres.
** Puede ser una serie de una o más etiquetas, con etiquetas adyacentes separadas por un punto. Cada etiqueta debe comenzar y terminar con una letra minúscula o un número y solo puede utilizar letras minúsculas, números y guiones.
** No debe ser una dirección IP con formato de texto.
** No debe utilizar periodos en solicitudes de estilo alojadas virtuales. Los períodos provocarán problemas en la verificación del certificado comodín del servidor.


* De forma predeterminada, los bloques se crean en la `us-east-1` región; sin embargo, puede utilizar la `LocationConstraint` elemento de solicitud en el cuerpo de solicitud para especificar una región diferente. Cuando utilice la `LocationConstraint` Elemento, debe especificar el nombre exacto de una región que se ha definido mediante el Administrador de grid o la API de gestión de grid. Póngase en contacto con el administrador del sistema si no conoce el nombre de región que debe utilizar.
+
*Nota*: Se producirá un error si la solicitud PUT Bucket utiliza una región que no se ha definido en StorageGRID.

* Puede incluir el `x-amz-bucket-object-lock-enabled` Solicite el encabezado para crear un bucket con el bloqueo de objetos S3 habilitado. Consulte link:../s3/use-s3-api-for-s3-object-lock.html["Use la API REST DE S3 para configurar el bloqueo de objetos de S3"].
+
Debe habilitar S3 Object Lock cuando crea el bloque. No puede agregar o deshabilitar S3 Object Lock después de crear un bucket. S3 Object Lock requiere el control de versiones de bloques, que se habilita automáticamente al crear el bloque.





 a| 
COLOQUE los cors del cucharón
 a| 
Esta operación establece la configuración de CORS para un cucharón para que éste pueda atender solicitudes de origen cruzado. El uso compartido de recursos de origen cruzado (CORS) es un mecanismo de seguridad que permite a las aplicaciones web de cliente de un dominio acceder a los recursos de un dominio diferente. Por ejemplo, supongamos que se utiliza un bloque de S3 llamado `images` para almacenar gráficos. Mediante el ajuste de la configuración de CORS para `images` bloque, puede permitir que las imágenes de ese bloque se muestren en el sitio web `+http://www.example.com+`.



 a| 
PUT Bucket Encryption
 a| 
Esta operación establece el estado de cifrado predeterminado de un bloque existente. Cuando se habilita el cifrado a nivel de bloque, se cifran todos los objetos nuevos que se añadan al bloque.StorageGRID admite el cifrado en el lado del servidor con claves gestionadas por StorageGRID. Al especificar la regla de configuración de cifrado del servidor, defina la `SSEAlgorithm` parámetro a. `AES256`, y no utilice el `KMSMasterKeyID` parámetro.

La configuración de cifrado predeterminada de bloque se omite si la solicitud de carga de objeto ya especifica cifrado (es decir, si la solicitud incluye la `x-amz-server-side-encryption-*` encabezado de solicitud).



 a| 
CICLO de vida DE la cuchara

(PutBucketLifecycleConfiguration)
 a| 
Esta operación crea una nueva configuración del ciclo de vida para el bloque o reemplaza una configuración de ciclo de vida existente. StorageGRID admite hasta 1,000 reglas de ciclo de vida en una configuración del ciclo de vida. Cada regla puede incluir los siguientes elementos XML:

* Caducidad (días, fecha)
* NoncurrentVersionExpiración (NoncurrentDays)
* Filtro (prefijo, etiqueta)
* Estado
* ID


StorageGRID no admite estas acciones:

* AbortEncompleteMultipartUpload
* ExpiredObjectDeleteMarker
* Transición


Consulte link:create-s3-lifecycle-configuration.html["Cree una configuración del ciclo de vida de S3"]. Para comprender cómo la acción de caducidad en un ciclo de vida de bloques interactúa con las instrucciones de ubicación de ILM, consulte link:../ilm/how-ilm-operates-throughout-objects-life.html["Cómo funciona ILM a lo largo de la vida de un objeto"].

*Nota*: La configuración del ciclo de vida de la cuchara se puede utilizar con cucharones que tengan habilitado el bloqueo de objetos S3, pero la configuración del ciclo de vida de la cuchara no es compatible con cucharones legados compatibles.



 a| 
NOTIFICACIÓN DE PUT Bucket

(PutBucketNotificationConfiguration)
 a| 
Esta operación configura notificaciones para el bloque mediante el XML de configuración de notificación incluido en el cuerpo de la solicitud. Debe tener en cuenta los siguientes detalles de implementación:

* StorageGRID admite temas como destinos el Servicio de notificación simple (SNS). No se admiten los puntos finales de Simple Queue Service (SQS) o Amazon Lambda.
* El destino de las notificaciones debe especificarse como URN de un extremo de StorageGRID. Se pueden crear extremos con el administrador de inquilinos o la API de gestión de inquilinos.
+
El extremo debe existir para que la configuración de la notificación se realice correctamente. Si el extremo no existe, un `400 Bad Request` se devuelve un error con el código `InvalidArgument`.

* No puede configurar una notificación para los siguientes tipos de evento. Estos tipos de evento *no* son compatibles.
+
** `s3:ReducedRedundancyLostObject`
** `s3:ObjectRestore:Completed`


* Las notificaciones de eventos enviadas desde StorageGRID utilizan el formato JSON estándar, excepto que no incluyen algunas claves y utilizan valores específicos para otros, como se muestra en la lista siguiente:
+
** *EventSource*
+
`sgws:s3`

** * AwsRegion*
+
no incluido

** *x-amz-id-2*
+
no incluido

** *arn*
+
`urn:sgws:s3:::bucket_name`







 a| 
POLÍTICA DE PUT Bucket
 a| 
Esta operación establece la política asociada al bloque.



 a| 
PUT Bucket replication
 a| 
Esta operación configura link:../tenant/understanding-cloudmirror-replication-service.html["Replicación de CloudMirror de StorageGRID"] Para el depósito que utiliza el XML de configuración de replicación proporcionado en el cuerpo de la solicitud. Para la replicación de CloudMirror, debe tener en cuenta los siguientes detalles de la implementación:

* StorageGRID solo admite V1 de la configuración de replicación. Esto significa que StorageGRID no admite el uso de `Filter` Elemento para reglas y sigue las convenciones V1 para eliminar versiones de objetos. Para obtener más detalles, consulte https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication-add-config.html["Documentación de Amazon S3 en la configuración de la replicación"^].
* La replicación de bloques se puede configurar en bloques con versiones o sin versiones.
* Puede especificar un segmento de destino diferente en cada regla del XML de configuración de replicación. Un bloque de origen puede replicar en más de un bloque de destino.
* Los bloques de destino se deben especificar como URN de extremos StorageGRID tal y como se especifica en el administrador de inquilinos o la API de gestión de inquilinos. Consulte link:../tenant/configuring-cloudmirror-replication.html["Configure la replicación de CloudMirror"].
+
El extremo debe existir para que la configuración de replicación se complete correctamente. Si el extremo no existe, la solicitud falla como un `400 Bad Request`. El mensaje de error indica: `Unable to save the replication policy. The specified endpoint URN does not exist: _URN_.`

* No es necesario especificar un `Role` En el XML de configuración. StorageGRID no utiliza este valor y se ignorará si se envía.
* Si omite la clase de almacenamiento del XML de configuración, StorageGRID utiliza `STANDARD` clase de almacenamiento de forma predeterminada.
* Si elimina un objeto del bloque de origen o elimina el propio bloque de origen, el comportamiento de replicación entre regiones es el siguiente:
+
** Si elimina el objeto o bloque antes de que se haya replicado, el objeto o bloque no se replicará y no se le notificará.
** Si elimina el objeto o bloque después de haber sido replicado, StorageGRID sigue el comportamiento estándar de eliminación de Amazon S3 para V1 de replicación entre regiones.






 a| 
PUT Bucket etiquetaje
 a| 
Esta operación utiliza `tagging` subrecurso para agregar o actualizar un conjunto de etiquetas para un bloque. Al añadir etiquetas de bloque, tenga en cuenta las siguientes limitaciones:

* Tanto StorageGRID como Amazon S3 admiten hasta 50 etiquetas por cada bloque.
* Las etiquetas asociadas con un bloque deben tener claves de etiqueta únicas. Una clave de etiqueta puede tener hasta 128 caracteres Unicode de longitud.
* Los valores de etiqueta pueden tener una longitud máxima de 256 caracteres Unicode.
* La clave y los valores distinguen entre mayúsculas y minúsculas.




 a| 
PONER creación de versiones de bloques
 a| 
Esta implementación usa la `versioning` subrecurso para establecer el estado de control de versiones de un bloque existente. Puede establecer el estado de control de versiones con uno de los siguientes valores:

* Enabled: Activa el control de versiones de los objetos del bloque. Todos los objetos que se agregan al bloque reciben un ID de versión único.
* Suspendido: Desactiva el control de versiones de los objetos del bloque. Todos los objetos agregados al bloque reciben el ID de versión `null`.




 a| 
PONER configuración de bloqueo de objeto
 a| 
Esta operación configura o elimina el modo de retención predeterminado de bloque y el período de retención predeterminado.

Si se modifica el período de retención predeterminado, la fecha de retención hasta la de las versiones de objeto existentes seguirá siendo la misma y no se volverá a calcular utilizando el nuevo período de retención predeterminado.

Consulte link:../s3/use-s3-api-for-s3-object-lock.html["Use la API REST DE S3 para configurar el bloqueo de objetos de S3"] para obtener información detallada.

|===
.Información relacionada
link:consistency-controls.html["Controles de consistencia"]

link:get-bucket-last-access-time-request.html["HORA de último acceso al bloque DE GET"]

link:bucket-and-group-access-policies.html["Utilice las políticas de acceso de bloques y grupos"]

link:s3-operations-tracked-in-audit-logs.html["Se realizó un seguimiento de las operaciones de S3 en los registros de auditoría"]
