---
permalink: s3/post-object-restore.html 
sidebar: sidebar 
keywords: post, post object restore, object 
summary: Puede usar la solicitud DE restauración DE objetos POST de S3 PARA restaurar un objeto almacenado en un pool de almacenamiento en cloud. 
---
= Restauración DE objetos posterior
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar la solicitud DE restauración DE objetos POST de S3 PARA restaurar un objeto almacenado en un pool de almacenamiento en cloud.



== Tipo de solicitud admitido

StorageGRID solo admite solicitudes POSTERIORES a la restauración de objetos para restaurar un objeto. No admite la `SELECT` tipo de restauración. Seleccione solicitudes de devolución `XNotImplemented`.



== Creación de versiones

Opcionalmente, especifique `versionId` para restaurar una versión específica de un objeto en un bloque con versiones. Si no especifica `versionId`, se restaura la versión más reciente del objeto



== Comportamiento de la restauración POSTERIOR de objetos en objetos de Pool de almacenamiento en cloud

Si un objeto se ha almacenado en un Cloud Storage Pool (consulte las instrucciones para gestionar objetos con gestión del ciclo de vida de la información), una solicitud POSTERIOR de restauración de objetos tiene el siguiente comportamiento, en función del estado del objeto. Consulte «'HEAD Object'» para obtener más información.


NOTE: Si un objeto se almacena en un Cloud Storage Pool y existen también una o varias copias del objeto en la cuadrícula, no es necesario restaurar el objeto mediante la emisión de una solicitud DE restauración DE objetos POSTERIOR. En su lugar, la copia local se puede recuperar directamente, utilizando UNA solicitud GET Object.

[cols="1a,2a"]
|===
| Estado del objeto | Comportamiento DE la restauración POSTERIOR de objetos 


 a| 
El objeto se ingiere en StorageGRID pero aún no se ha evaluado por ILM, o el objeto no está en un pool de almacenamiento cloud
 a| 
`403 Forbidden`, `InvalidObjectState`



 a| 
Objeto en el pool de almacenamiento en cloud pero todavía no ha realizado la transición a un estado no recuperable
 a| 
`200 OK` No se han realizado cambios.

*Nota*: Antes de que un objeto haya pasado a un estado no recuperable, no puedes cambiarlo `expiry-date`.



 a| 
Objeto que ha pasado a un estado no recuperable
 a| 
`202 Accepted` Restaura una copia recuperable del objeto en el Pool de almacenamiento en la nube durante la cantidad de días especificada en el cuerpo de la solicitud. Al final de este período, el objeto se devuelve a un estado no recuperable.

Opcionalmente, utilice la `Tier` solicitar elemento para determinar cuánto tiempo tardará el trabajo de restauración en finalizar (`Expedited`, `Standard`, o. `Bulk`). Si no especifica `Tier`, la `Standard` se utiliza el nivel.

*Importante*: Si un objeto ha sido trasladado a S3 Glacier Deep Archive o el Cloud Storage Pool utiliza almacenamiento de Azure Blob, no puede restaurarlo con el `Expedited` nivel. Se devuelve el siguiente error `403 Forbidden`, `InvalidTier`: `Retrieval option is not supported by this storage class`.



 a| 
Objeto en proceso de restauración a partir de un estado no recuperable
 a| 
`409 Conflict`, `RestoreAlreadyInProgress`



 a| 
Objeto completamente restaurado en el pool de almacenamiento en cloud
 a| 
`200 OK`

*Nota:* Si un objeto ha sido restaurado a un estado recuperable, usted puede cambiar su `expiry-date` Volviendo a emitir la solicitud DE restauración DE objeto POSTERIOR con un nuevo valor para `Days`. La fecha de restauración se actualiza en relación con la hora de la solicitud.

|===
.Información relacionada
link:../ilm/index.html["Gestión de objetos con ILM"]

link:head-object.html["OBJETO HEAD"]

link:s3-operations-tracked-in-audit-logs.html["Se realizó un seguimiento de las operaciones de S3 en los registros de auditoría"]
