---
permalink: s3/put-bucket-consistency-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, PUT bucket consistency request 
summary: La solicitud PUT Bucket Consistency permite especificar el nivel de coherencia que se va a aplicar a las operaciones realizadas en un bloque. 
---
= PONGA la consistencia del cucharón
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La solicitud PUT Bucket Consistency permite especificar el nivel de coherencia que se va a aplicar a las operaciones realizadas en un bloque.

Los controles de consistencia predeterminados se establecen para garantizar la lectura tras escritura de los objetos recién creados.

.Antes de empezar
Tiene el permiso s3:PutBucketConsistency, o bien sea raíz de la cuenta, para completar esta operación.



== Solicitud

La `x-ntap-sg-consistency` el parámetro debe contener uno de los siguientes valores:

[cols="1a,2a"]
|===
| Control de consistencia | Descripción 


 a| 
todo
 a| 
Todos los nodos reciben los datos inmediatamente o se produce un error en la solicitud.



 a| 
fuerte en todo el mundo
 a| 
Garantiza la coherencia de lectura tras escritura para todas las solicitudes del cliente en todos los sitios.



 a| 
sitio seguro
 a| 
Garantiza la coherencia de lectura tras escritura para todas las solicitudes del cliente dentro de un sitio.



 a| 
lectura-después-nueva-escritura
 a| 
(Predeterminado) proporciona coherencia de lectura tras escritura para los nuevos objetos y coherencia final para las actualizaciones de objetos. Ofrece garantías de alta disponibilidad y protección de datos. Recomendado para la mayoría de los casos.



 a| 
disponible
 a| 
Proporciona consistencia eventual tanto para nuevos objetos como para actualizaciones de objetos. Para los cubos S3, utilice solo según sea necesario (por ejemplo, para un depósito que contiene valores de registro que rara vez se leen, o para operaciones HEAD u GET en claves que no existen). No se admite para bloques de FabricPool S3.

|===
*Nota:* en general, se debe utilizar el valor de control de la coherencia "read-after-new-write". Si las solicitudes no funcionan correctamente, cambie el comportamiento del cliente de aplicación si es posible. O bien, configure el cliente para especificar el control de consistencia de cada solicitud API. Establecer el control de consistencia a nivel de cucharón únicamente como último recurso.



== Ejemplo de solicitud

[listing, subs="specialcharacters,quotes"]
----
PUT /bucket?x-ntap-sg-consistency=strong-global HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----
.Información relacionada
link:consistency-controls.html["Controles de consistencia"]
