---
permalink: monitor/manually-triggering-autosupport-message.html 
sidebar: sidebar 
keywords: autosupport, triggering autosupport, manually triggering autosupport, autosupport triggers 
summary: Con el fin de ayudar al soporte técnico a solucionar problemas con su sistema StorageGRID, puede activar manualmente el envío de un mensaje de AutoSupport. 
---
= Active manualmente un mensaje de AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Con el fin de ayudar al soporte técnico a solucionar problemas con su sistema StorageGRID, puede activar manualmente el envío de un mensaje de AutoSupport.

.Antes de empezar
* Debe iniciar sesión en Grid Manager mediante un link:../admin/web-browser-requirements.html["navegador web compatible"].
* Debe tener el acceso root u otro permiso de configuración de grid.


.Pasos
. Seleccione *SUPPORT* > *Tools* > *AutoSupport*.
. En la pestaña *Configuración*, selecciona *Enviar AutoSupport activado por el usuario*.
+
StorageGRID intenta enviar un mensaje de AutoSupport al soporte técnico. Si el intento se realiza correctamente, se actualizan los valores *resultado más reciente* y *tiempo más reciente* de la ficha *resultados*. Si hay algún problema, el valor del *resultado más reciente* se actualiza a "error" y StorageGRID no intenta volver a enviar el mensaje AutoSupport.

+

NOTE: Después de enviar un mensaje AutoSupport activado por el usuario, actualice la página AutoSupport en el explorador después de 1 minuto para acceder a los resultados más recientes.


